### ISSUE TITLE
http头不标准时崩溃

### ISSUE THREAD

**Issue by TooBug** [TooBug/CharlesX#1]
```
_http_outgoing.js:348
    throw new TypeError('The header content contains invalid characters');
    ^

TypeError: The header content contains invalid characters
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:348:11)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\charlesx\node_modules\http-proxy\lib\http-proxy\passes\web-outgoing.js:86:13
    at Array.forEach (native)
    at Array.writeHeaders (C:\Users\Administrator\AppData\Roaming\npm\node_modules\charlesx\node_modules\http-proxy\lib\http-proxy\passes\web-outgoing.js:84:35)
    at ClientRequest.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\charlesx\node_modules\http-proxy\lib\http-proxy\passes\web-incoming.js:157:20)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:469:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:105:23)
    at Socket.socketOnData (_http_client.js:359:20)

```

**Comment by TooBug** [comment]
https://github.com/nodejitsu/node-http-proxy/issues/964
